// NosEmu
// 


namespace WingsEmu.Game.Buffs;

public enum BCardType : short
{
    // 1-20
    SpecialAttack = 1,
    SpecialDefence = 2,
    AttackPower = 3,
    Target = 4,
    Critical = 5,
    SpecialCritical = 6,
    Element = 7,
    IncreaseDamage = 8,
    Defence = 9,
    DodgeAndDefencePercent = 10,
    Block = 11,
    Absorption = 12,
    ElementResistance = 13,
    EnemyElementResistance = 14,
    Damage = 15,
    GuarantedDodgeRangedAttack = 16,
    Morale = 17,
    Casting = 18,
    Move = 19,
    Reflection = 20,

    // 21-40
    DrainAndSteal = 21,
    HealingBurningAndCasting = 22,
    HPMP = 23,
    SpecialisationBuffResistance = 24,
    Buff = 25,
    Summons = 26,
    SpecialEffects = 27,
    Capture = 28,
    SpecialDamageAndExplosions = 29,
    SpecialEffects2 = 30,
    CalculatingLevel = 31,
    Recovery = 32,
    MaxHPMP = 33,
    MultAttack = 34,
    MultDefence = 35,
    TimeCircleSkills = 36,
    RecoveryAndDamagePercent = 37,
    Count = 38,
    NoDefeatAndNoDamage = 39,
    SpecialActions = 40,

    // 41-60
    Mode = 41,
    NoCharacteristicValue = 42,
    LightAndShadow = 43,
    Item = 44,
    DebuffResistance = 45,
    SpecialBehaviour = 46,
    Quest = 47,
    SecondSPCard = 48,
    SPCardUpgrade = 49,
    DamageInflict = 50,
    Drain = 51,
    LordMorcos = 52,
    LordHatus = 53,
    LordCalvinas = 54,
    SESpecialist = 55,
    LordBerios = 56,
    FourthGlacernonFamilyRaid = 57,
    BearSpirit = 58,
    SummonSkill = 59,
    InflictSkill = 60,

    // 61-80 
    VoodooPriest = 61,
    HideBarrelSkill = 62,
    FocusEnemyAttentionSkill = 63,
    TauntSkill = 64,
    FireCannoneerRangeBuff = 65,
    VulcanoElementBuff = 66,
    DamageConvertingSkill = 67,
    MeditationSkill = 68,
    FalconSkill = 69,
    AbsorptionAndPowerSkill = 70,
    LeonaPassiveSkill = 71,
    FearSkill = 72,
    SniperAttack = 73,
    FrozenDebuff = 74,
    JumpBackPush = 75,
    Other = 76,
    SummonAndRecoverHP = 77,
    TeamArenaBuff = 78,
    ArenaCamera = 79,
    DarkCloneSummon = 80,

    // 81-100
    AbsorbedSpirit = 81,
    AngerSkill = 82,
    MeteoriteTeleport = 83,
    StealBuff = 84,
    ChangingPlace = 85,
    EffectSummon = 86,
    ReputHeroLevel = 87,
    BackToMiniland = 88,
    DragonSkills = 89,
    IncreaseDamageVersus = 90,
    MysticArts = 91,
    MysticArtsTransformed = 92,
    IncreaseElementProcent = 93,
    IncreaseElementByResis = 94,
    DropItemTwice = 95,
    IncreaseElementFairy = 96,
    IncreaseDamageDebuffs = 97,
    IncreaseElementDamage = 98,
    IncreaseDamageVersusMonsters = 99,
    IncreaseDamageVersusMonsters_2 = 100,

    // 101-??
    IncreaseDamageInLoD = 101,
    IncreaseSpPoints = 102,
    IncreaseAllDamage = 103,
    DealDamageAround = 104,
    CarvedRunes = 105,
    CarvedRunes2 = 106,
    MagicArmour = 107,
    ReflectDamage = 108,
    Tattoo = 109,
    KingOfTheBeast = 110,
    GetInDodge = 111,
    SquadAndGravity = 113,
    IncreaseDamageByElement = 114,
    Fishing = 115,
    CarvedRunes3 = 116,
    CarvedRunes4 = 117,
    DefencePiercing = 118,
    BlasterHeat = 119,
    Energy = 120,
    ConditionalEffects = 121,
    FuelHeatPoint = 122,
    PetTames = 123,
    TokenBasedAbilities = 124,
    MineralTokenEffects = 125,
    PyrosphereTokenEffects = 126,
    SpareBatteryTokenEffects = 127,

    // NosEmu custom
    
    //Custom DMG
    CustomEventPercentageDamage = 313,
    
    RainbowBattleEffects = 300,
    HPMPRecoverWhileDefending = 301,
    Act4DungeonElemental = 302,
    AntiMagicDisorder = 303,
    AllExperienceGain = 304,
    BuffWhenOverwhelmed = 305,
    Reputation = 306,
    TargetAreaAttackSkills = 307,
    DamageProbaMonster = 308,
    IncreaseDamageTrophy = 309,
    PvPDodge = 310,
    IncreaseDamageVersusMonsters_3 = 311,
    RockyHelmetArmour = 312,
    
}