namespace WingsEmu.Game.EntityStatistics;

public enum Statistics
{
    MIN_DAMAGE,
    MAX_DAMAGE,
    HITRATE,
    CRITICAL_CHANCE,
    CRITICAL_DAMAGE,
    SECOND_MIN_DAMAGE,
    SECOND_MAX_DAMAGE,
    SECOND_HITRATE,
    SECOND_CRITICAL_CHANCE,
    SECOND_CRITICAL_DAMAGE,
    MELEE_DEFENSE,
    RANGE_DEFENSE,
    MAGIC_DEFENSE,
    MELEE_DODGE,
    RANGE_DODGE,
    FIRE_RESISTANCE,
    WATER_RESISTANCE,
    LIGHT_RESISTANCE,
    SHADOW_RESISTANCE
}

public enum PassiveType
{
    HP,
    MP,
    MELEE_ATTACK,
    RANGED_ATTACK,
    MAGIC_ATTACK,
    REGEN_HP,
    REGEN_MP,
    PASSIVE_REGEN,
    MELEE_DEFENCE,
    RANGED_DEFENCE,
    MAGIC_DEFENCE,
    MELEE_HIRATE,
    RANGED_HIRATE,
    MELEE_DODGE,
    RANGED_DODGE,

    // HERO BOOK
    PVP_DAMAGE_HERO_BOOK,
    PVP_DEFENCE_HERO_BOOK,
    ALL_ELEMENT_RESISTANCES_HERO_BOOK,
    EXPERIENCE_HERO_BOOK,
    GOLD_HERO_BOOK,
}