namespace WingsAPI.Packets.Enums
{
    public enum EvtbType : byte
    {
        INCREASE_CHANCE_UPGRADE_EQUIPMENT, // %
        INCREASE_CHANCE_GAMBLING_EQUIPMENT, // %
        INCREASE_CHANCE_UPGRADE_SPECIALIST, // %
        INCREASE_CHANCE_UPGRADE_SP_PERFECTION, // %
        INCREASE_FAMILY_XP_EARNED, // %
        IS_SEALED_EVENT_ACTIVE, // True or False
        INCREASE_EXPERIENCE_EARNED, // Multiply
        INCREASE_GOLD_EARNED, // Multiply
        INCREASE_REPUTATION_EARNED, // Multiply
        INCREASE_ITEM_DROP_CHANCE, // Multiply
        INCREASE_CHANCE_UPGRADE_RUNES, // %
        INCREASE_CHANCE_UPGRADE_TATTOOS, // %
        INCREASE_FISHING_EXPERIENCE_GAIN, // %
        INCREASE_COOKING_EXPERIENCE_GAIN, // %
        INCREASE_CHANCE_GET_SECOND_RAIDBOX, // %
        INCREASE_FULLNESS_POINTS_RECEIVED, // %
        INCREASE_CHANCE_GET_HIGHER_PARTNER_SKILLS, // %
        INCREASE_PARTNER_CARD_FUSION, // %
        INCREASE_PET_TRAINER_EXPERIENCE, // %
        INCREASE_CHANCE_FAIRY_UPGRADE, // %
        NONE
    }
}