namespace WingsAPI.Packets.Enums;

public enum NpcDialogType : int
{
    CHANGE_SUBCLASS_BASIC_SWORDMAN = 30001,
    CHANGE_SUBCLASS_BASIC_ARCHER = 30002,
    CHANGE_SUBCLASS_BASIC_MAGICIAN = 30003,
    CHANGE_SUBCLASS_BASIC_MARTIAL_ARTIST = 30004,
    CHANGE_SUBCLASS_PREMIUM_SWORDMAN = 30005,
    CHANGE_SUBCLASS_PREMIUM_ARCHER = 30006,
    CHANGE_SUBCLASS_PREMIUM_MAGICIAN = 30007,
    CHANGE_SUBCLASS_PREMIUM_MARTIAL_ARTIST = 30008,
}